# Makefile for GNU cpio library.

# Copyright (C) 2004 Free Software Foundation, Inc.

## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2, or (at your option)
## any later version.

## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
## 02111-1307, USA.

noinst_LIBRARIES = libcpio.a
noinst_HEADERS = system.h localedir.h rmt.h
libcpio_a_SOURCES = rtapelib.c

EXTRA_DIST=Makefile.tmpl bcopy.c mkdir.c strdup.c strerror.c

localedir = $(datadir)/locale

DISTCLEANFILES = localedir.h
localedir.h : Makefile
	echo '#define LOCALEDIR "$(localedir)"' >$@
	echo "#ifndef DEFAULT_RMT_COMMAND" >> $@
	echo "# define DEFAULT_RMT_COMMAND \"$(DEFAULT_RMT_DIR)/`echo \"rmt\" | sed 's,^.*/,,;$(transform)'`$(EXEEXT)\"" >> $@
	echo "#endif" >> $@

libcpio_a_LIBADD = $(LIBOBJS) $(ALLOCA)
libcpio_a_DEPENDENCIES = $(libcpio_a_LIBADD)

rtapelib.o: localedir.h

BUILT_SOURCES =
MAINTAINERCLEANFILES =
MOSTLYCLEANFILES =
lib_OBJECTS = $(libcpio_a_OBJECTS)

# gnulib modules

